config/routes.rb
Brandscopic::Application.routes.draw do

  apipie if ENV['WEB']

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end

        resources :events, only: [:index, :show, :create, :update] do
          resources :photos, only: [:index, :create, :update] do
            get :form, on: :collection
          end
          resources :event_expenses, only: [:index, :create] do
            get :form, on: :collection
          end
          resources :tasks, only: [:index]
          resources :comments, only: [:index, :create, :update, :destroy]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
          end
        end

        # To allow CORS for any API action
        match ':path1(/:path2(/:path3(/:path4)))', via: :options, to: 'api#options'

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          get :stats, on: :member
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [] do
          member do
            get :comments
          end
          collection do
            get :mine, to: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, to: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end
      end
    end
  end

  if ENV['WEB']
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    mount Resque::Server.new, at: '/resque' unless Rails.env.test?
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  get '/users/complete-profile', to: 'users#complete', as: :complete_profile
  put '/users/update-profile', to: 'users#update_profile', as: :update_profile
  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }

  get 'countries/states'

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  namespace :results do
    resources :event_data, only: [:index] do
      get :items, on: :collection
    end
    resources :comments, only: [:index] do
      get :items, on: :collection
    end
    resources :photos, only: [:index] do
      get :items, on: :collection
      get :autocomplete, on: :collection
      get :filters, on: :collection
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :expenses, only: [:index] do
      get :items, on: :collection
    end
    resources :surveys, only: [:index] do
      get :items, on: :collection
    end
    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    resources :reports, only: [:index, :new, :create, :edit, :update, :show] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      get :deactivate, on: :member
      get :activate, on: :member
      post :preview, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'
    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'
  end

  namespace :analysis do
    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'
  end

  scope '/research' do
    resources :venues, only: [:index, :show] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      get :filters, on: :collection
      get :items, on: :collection
      resources :events, only: [:new, :create]
      resources :activities, only: [:new, :create] do
        get :form, on: :collection
      end
    end
  end

  resources :roles, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
    end
  end

  resources :company_users, except: [:new, :create, :destroy], path: 'users' do
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    get :profile, on: :collection
    get :autocomplete, on: :collection
    get :time_zone_change, on: :collection
    post :time_zone_change, on: :collection
    put :time_zone_update, on: :collection
    get :event, via: :get, on: :collection # List of users by event
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    resources :goals, only: [:create, :update, :edit, :new]
    resources :tasks do
      member do
        get :deactivate
        get :activate
      end
    end
    member do
      post :verify_phone
      get :send_code
      get :deactivate
      get :activate
      post :enable_campaigns
      post :disable_campaigns
      get :select_campaigns
      delete :remove_campaign
      post :add_campaign
      get :edit_communications
    end
  end

  resources :teams, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
      match 'members/:member_id' => 'teams#delete_member', via: :delete, as: :delete_member
      match 'members/new' => 'teams#new_member', via: :get, as: :new_member
      match 'members' => 'teams#add_members', via: :post, as: :add_member
    end
  end

  resources :kpis, only: [:index]

  resources :campaigns, except: [:destroy] do
    resources :areas_campaigns, only: [:edit, :update] do
      post :exclude_place, on: :member
      post :include_place, on: :member
    end

    resources :brands, only: [:index]
    resources :kpis, only: [:new, :create, :edit, :update]
    resources :activity_types, only: [] do
      get :set_goal
    end
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html
    get :find_similar_kpi, on: :collection
    member do
      get :post_event_form
      post :update_post_event_form
      get :deactivate
      get :activate
      get :places
      match 'members/:member_id' => 'campaigns#delete_member', via: :delete, as: :delete_member
      match 'teams/:team_id' => 'campaigns#delete_member', via: :delete, as: :delete_team
      match 'members/new' => 'campaigns#new_member', via: :get, as: :new_member
      match 'members' => 'campaigns#add_members', via: :post, as: :add_member
      match 'members' => 'campaigns#members', via: :get, as: :members
      match 'teams' => 'campaigns#teams', via: :get, as: :teams
      match 'tab/:tab' => 'campaigns#tab', via: :get, as: :tab, constraints: { tab: /staff|places|date_ranges|day_parts|documents|kpis/ }

      match 'date_ranges/new' => 'campaigns#new_date_range', via: :get, as: :new_date_range
      match 'date_ranges' => 'campaigns#add_date_range', via: :post, as: :add_date_range

app/controllers/results/comments_controller.rb
class Results::CommentsController < FilteredController
  defaults resource_class: ::Event
  respond_to :xls, only: :index

  helper_method :return_path

  private

  def search_params
    @search_params ||= begin
      super
      unless @search_params.key?(:user) && !@search_params[:user].empty?
        @search_params[:with_comments_only] = true
      end
      @search_params
    end
  end

  def authorize_actions
    authorize! :index_results, Comment
  end

  def return_path
    results_reports_path
  end
end

app/controllers/results/event_status_controller.rb
class Results::EventStatusController < ApplicationController
  before_action :campaign, except: :index
  before_action :authorize_actions

  helper_method :return_path, :report_group_by

  def report
    @data = if report_group_by == 'campaign'
              Campaign.where(id: campaign.id).promo_hours_graph_data
    elsif report_group_by == 'place'
              @campaign.event_status_data_by_areas(current_company_user)
    elsif report_group_by == 'staff'
              @campaign.event_status_data_by_staff
    end
  end

  private

  def campaign
    @campaign ||= current_company.campaigns.find(params[:report][:campaign_id])
  end

  def authorize_actions
    if params[:report] && params[:report][:campaign_id]
      authorize! :event_status_report_campaign, campaign
    else
      authorize! :event_status, Campaign
    end
  end

  def return_path
    results_reports_path
  end

  def report_group_by
    @_view_mode ||= if params[:report] && params[:report][:group_by]
                      params[:report][:group_by]
    else
      'campaign'
    end
  end
end

app/controllers/results/expenses_controller.rb
class Results::ExpensesController < FilteredController
  defaults resource_class: ::Event
  respond_to :xls, only: :index

  helper_method :expenses_total, :return_path

  private

  def search_params
    @search_params ||= begin
      super
      unless @search_params.key?(:user) && !@search_params[:user].empty?
        @search_params[:with_expenses_only] = true
      end
      @search_params[:event_data_stats] = true
      @search_params
    end
  end

  def expenses_total
    @solr_search.stat_response['stats_fields']['spent_es']['sum'] rescue 0
  end

  def authorize_actions
    authorize! :index_results, EventExpense
  end

  def return_path
    results_reports_path
  end
end

app/helpers/results/event_data_helper.rb
module Results
  module EventDataHelper
    def custom_fields_to_export_headers
      @_headers ||= custom_columns.values.map(&:upcase)
    end

    def custom_fields_to_export_values(event)
      # We are reusing the same object for each result to reduce memory usage
      @result ||= FormFieldResult.new
      event_values = empty_values_hash
      ActiveRecord::Base.connection.select_all(ActiveRecord::Base.connection.unprepared_statement do
        event.results.where(form_field_id: active_fields_for_campaign(event.campaign_id))
                  .select('form_field_results.form_field_id, form_field_results.value, form_field_results.hash_value').to_sql
      end).each do |row|
        @result.form_field = custom_fields_to_export[row['form_field_id'].to_i]
        if @result.form_field.is_hashed_value?
          @result.hash_value = row['hash_value']
        else
          @result.value = row['value']
        end
        id = @result.form_field.kpi_id.nil? ? "field_#{@result.form_field_id}" : "kpi_#{@result.form_field.kpi_id}"
        if @result.form_field.type == 'FormField::Percentage'
          # values = ActiveRecord::Coders::Hstore.load(row['hash_value'])
          # TODO: we have to correctly map values for hash_value here
          @result.form_field.options_for_input.each do |option|
            value = @result.value[option[1].to_s]
            event_values["#{id}-#{option[1]}"] = ['Number', 'percentage', (value.present? && value != '' ? value.to_f : 0.0) / 100]
          end
        else
          event_values[id] = if @result.form_field.is_numeric?
                               ['Number', 'normal', (Float(@result.to_csv) rescue nil)]
          else
            ['String', 'normal', @result.to_csv]
          end
        end
      end
      event_values.values
    end

    def area_for_event(event)
      campaign_from_cache(event.campaign_id).areas_campaigns.select do|ac|
        ac.place_in_scope?(event.place)
      end.map { |ac| ac.area.name }.join(', ') unless event.place.nil?
    end

    def team_member_for_event(event)
      ActiveRecord::Base.connection.unprepared_statement do
        ActiveRecord::Base.connection.select_values("
          #{event.users.joins(:user).select('users.first_name || \' \' || users.last_name AS name').reorder(nil).to_sql}
          UNION ALL
          #{event.teams.select('teams.name').reorder(nil).to_sql}
          ORDER BY name
        ").join(', ')
      end
    end

    def url_for_event(event)
      Rails.application.routes.url_helpers.event_url(event)
    end

    private

    # Returns an array of nils that need to be populated by the event
    # where the key is the id of the field + the id of the segment id if the field is segmentable
    def empty_values_hash
      @empty_values_hash ||= custom_columns.dup
      @empty_values_hash.each { |k, _v| @empty_values_hash[k] = nil }
      @empty_values_hash
    end

    # Returns and array of Form Field IDs that are assigned to a campaign
    def active_fields_for_campaign(campaign_id)
      @campaign_fields ||= {}
      @campaign_fields[campaign_id] ||= campaign_from_cache(campaign_id).form_fields.where(id: custom_fields_to_export.keys).pluck(:id)
      @campaign_fields[campaign_id]
    end

    def custom_fields_to_export
      @kpis_to_export ||= begin
        exclude_kpis = [Kpi.impressions.id, Kpi.interactions.id, Kpi.samples.id, Kpi.gender.id, Kpi.ethnicity.id]
        exclude_field_types = ['FormField::Attachment', 'FormField::Photo', 'FormField::Section']
        campaign_ids = []
        campaign_ids = params[:campaign] if params[:campaign] && params[:campaign].any?
        if params[:q].present? && match = /\Acampaign,([0-9]+)/.match(params[:q])
          campaign_ids += [match[1]]
        end
        campaign_ids = campaign_ids.uniq.compact
        unless current_company_user.is_admin?
          if campaign_ids.any?
            campaign_ids = campaign_ids.map(&:to_i) & current_company_user.accessible_campaign_ids
          else
            campaign_ids = current_company_user.accessible_campaign_ids
          end
        end
        if campaign_ids.any?
          fields_scope = FormField.for_events_in_company(current_company_user.company_id)
                          .where('form_fields.kpi_id not in (?) OR kpi_id is NULL', exclude_kpis)
                          .where.not(type: exclude_field_types)
                          .order('form_fields.name ASC')
          fields_scope = fields_scope.where(campaigns: { id: campaign_ids }) unless current_company_user.is_admin? && campaign_ids.empty?
          Hash[fields_scope.map { |field| [field.id, field] }]
        else
          {}
        end
      end
      @kpis_to_export
    end

    def custom_columns
      @custom_columns ||= Hash[*custom_fields_to_export.map do |id, field|
        if field.type == 'FormField::Percentage'
          if field.kpi_id.nil?
            field.options_for_input.map { |s| ["field_#{field.id}-#{s[1]}", "#{field.name}: #{s[0]}"] }
          else
            field.options_for_input.map { |s| ["kpi_#{field.kpi_id}-#{s[1]}", "#{field.kpi.name}: #{s[0]}"] }
          end
        else
          field.kpi_id.nil? ? ["field_#{id}", field.name] : ["kpi_#{field.kpi_id}", field.kpi.name]
        end
      end.flatten]
      @custom_columns
    end

    def campaign_from_cache(id)
      @_campaign_cache ||= {}
      @_campaign_cache[id] ||= Campaign.find(id)
      @_campaign_cache[id]
    end
  end
end

app/views/results/event_data/_download.html.slim
p We are processing your request, the download will start soon...
.progress.progress-striped.active
  .bar style="width: 100%"

app/views/results/event_data/_event_data.html.slim
- if event.event_data.present?
  div.resource-item id="event_data_#{event.id}"
    = link_to_if_permitted(:show, Event, event_path(event.id), id: "event-link-#{event.id}", class: 'resource-item-link event-data-row') do
      span.event-info
        b= event.campaign_name
        br>/
        .clean-date
          = format_date_range(event_date(event, :start_at), event_date(event, :end_at), date_separator: ' ')
        = place_address(event.place, false, ', ', ', ')
      .results-box-container
        span.event-data-column.promo-hours-box
          = number_with_precision(event.promo_hours, precision: 1)
        span.event-data-column.impressions-box
          - if event.event_data.impressions.present?
            = number_with_delimiter(event.event_data.impressions)
        span.event-data-column.interactions-box
          - if event.event_data.interactions.present?
            = number_with_delimiter(event.event_data.interactions)
        span.event-data-column.samples-box
          - if event.event_data.samples.present?
            = number_with_delimiter(event.event_data.samples)
        span.event-data-column.spent-box
          - if event.event_data.spent.present?
            = number_to_currency(event.event_data.spent)
        span.event-data-column.gender-female-box
          - if event.event_data.gender_female.present? && event.event_data.gender_male.present?
            = number_to_percentage(event.event_data.gender_female, precision: 0)
        span.event-data-column.gender-female-box
          - if event.event_data.gender_male.present?
            = number_to_percentage(event.event_data.gender_male, precision: 0)
        span.event-data-column.ethnicity-asian-box
          - if event.event_data.ethnicity_asian.present?
            = number_to_percentage(event.event_data.ethnicity_asian, precision: 0)
        span.event-data-column.ethnicity-black-box
          - if event.event_data.ethnicity_black.present?
            = number_to_percentage(event.event_data.ethnicity_black, precision: 0)
        span.event-data-column.ethnicity-hispanic-box
          - if event.event_data.ethnicity_hispanic.present?
            = number_to_percentage(event.event_data.ethnicity_hispanic, precision: 0)
        span.event-data-column.ethnicity-native-american-box
          - if event.event_data.ethnicity_native_american.present?
            = number_to_percentage(event.event_data.ethnicity_native_american, precision: 0)
        span.event-data-column.ethnicity-white-box
          - if event.event_data.ethnicity_white.present?
            = number_to_percentage(event.event_data.ethnicity_white, precision: 0)
    .clearfix

app/views/results/event_data/_help_tutorial.html.slim
- content_for :help_title do
  | The Results area includes the raw output from all events. You can view photos, surveys, post-event recaps and other data captured across a campaign and export it for additional analysis
.help-overlay-definitions
  div data-target="#application-content" data-intro="Click anywhere or press Esc to close" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="top: -26px;"
  div data-target=".collection-list-horizontal-scroll" data-intro="A summary of key statistics for currently selected events is shown at the top. Clicking on the arrows to the left and right will scroll through additional results fields" data-position="top" data-helper-class="chardinjs-dashed" data-tooltip-style="top: -91px; left: 478px; max-width: 350px; width: 350px;"
  div data-target="#search-box-filter" data-intro="Search for specific events" data-position="bottom" data-tooltip-style="left: 45px; top: 110px; width: 115px; padding: 0px;"
  div data-target=".dates-range-filter" data-intro="Days that have events scheduled are highlighted in red. Click and drag to see events for a selected date range" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 95px; left: -127px;"
  div data-target=".form-facet-filters" data-intro="Search for specific events by campaign, brand, and location" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 200px; left: -127px;"
  div data-target="#save-filters-btn" data-intro='Save frequently used filter combinations by clicking on the "Save Filter" button and use it in later sessions or with other campaigns' data-position="left" data-tooltip-style="top: -65px; left: -124px;"

app/views/results/event_data/_totals.html.slim
.events-box
  .pull-left
    .big-number
      = number_with_precision(data_totals['events_count'], precision: 0, separator: '.', delimiter: ',')
    = 'EVENTS'
.results-box-container
  span.event-data-column.promo-hours-box
    .big-number
      = number_with_precision(data_totals['promo_hours'], precision: 2, separator: '.', delimiter: ',')
    = 'PROMO HOURS'
  span.event-data-column.impressions-box
    .big-number
      = number_with_precision(data_totals['impressions'], precision: 0, separator: '.', delimiter: ',')
    = 'IMPRESSIONS'
  span.event-data-column.interactions-box
    .big-number
      = number_with_precision(data_totals['interactions'], precision: 0, separator: '.', delimiter: ',')
    = 'INTERACTIONS'
  span.event-data-column.samples-box
    .big-number
      = number_with_precision(data_totals['samples'], precision: 0, separator: '.', delimiter: ',')
    = 'SAMPLED'
  span.event-data-column.spent-box
    .big-number
      = number_to_currency(data_totals['spent'])
    = 'SPENT'
  span.event-data-column.gender-female-box
    .big-number
      = number_to_percentage(data_totals['gender_female'], precision: 0)
    | FEMALE
  span.event-data-column.gender-female-box
    .big-number
      = number_to_percentage(data_totals['gender_male'], precision: 0)
    | MALE
  span.event-data-column.ethnicity-asian-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_asian'], precision: 0)
    | ASIAN
  span.event-data-column.ethnicity-black-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_black'], precision: 0)
    .data-label
      | AFRICAN
      br>/
      | AMERICAN
  span.event-data-column.ethnicity-hispanic-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_hispanic'], precision: 0)
    .data-label
      | HISPANIC
      br>/
      | LATINO
  span.event-data-column.ethnicity-native-american-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_native_american'], precision: 0)
    .data-label
      | NATIVE
      br>/
      | AMERICAN
  span.event-data-column.ethnicity-white-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_white'], precision: 0)
    | WHITE

app/views/results/event_data/index.html.slim
= render_navigation(renderer: :bootstrap, level: 2, skip_if_empty: true, nav_class: 'nav-tabs')

= user_new_feature('results_event_data') do
  h5 Getting Started: Event Data Report
  a.close.btn-dismiss-alert.icon.icon-close href="#" title="Dismiss"
  a.video-thumbnail href="#" title="Play Video" data-video="//www.youtube.com/embed/EZr3hcqx6zI?rel=0" data-width="640" data-height="360"
    img src="#{image_path('video_arrow.png')}" width="70" height="70" /
  .feature-description
    p
      'The Event Data Report holds all of your post event data. Use this report to keep track of your executed events, review campaign performance, and export raw data to excel. Click on the video to the left for a quick overview or check out our
      a> href="http://support.brandscopic.com" target="_blank" support site
      | for more in depth info.

.sidebar#resource-filter-column
  #collection-list-filters

#main.main.with-details-close-bar
  = resource_details_bar("You are viewing the Event Data report. Click to close.")
  .tab-content
    #list-view.tab-pane.active
      #list-tools.row-fluid
        .pull-right
          button.btn.download.xlsx-download-link data-url="#{url_for(format: :xls)}" title="Download" data-disable-with="..."
            span.icon-download
          a.btn.fullscreen.fullscreen-link href="#" data-fullscreen-element='main' title="Fullscreen"
            span.icon-fullscreen
      .collection-list-horizontal-scroll
        #columns-scoller-arrows.hide
          .left-arrow
            a.icon-angle-left
          .right-arrow
            a.icon-angle-right
        #event-data-totals

      #event-data-list.resource-list
        div.placeholder
          p Select any filter to see results

= render partial: 'help_tutorial'

javascript:
  $('#collection-list-filters').filteredList({
    'source': '#{url_for(controller: 'results/event_data', action: :items)}',
    'filtersUrl': '#{filters_events_path(with_event_data_only: true, apply_to: controller_name)}',
    'listContainer': '#event-data-list',
    'sorting': 'start_at',
    'sorting_dir': 'asc',
    'autoLoad': true,
    'includeCalendars': true,
    'selectDefaultDate': false,
    'includeAutoComplete': true,
    'autoCompletePath': '#{autocomplete_events_path(format: :json)}',
    'applyTo': '#{controller_name}',
    'defaultParams': [{name: 'status[]', value: 'Active'}],
    'clearFilterParams': [{name: 'status[]', value: 'Active'}],
    'onChange': function(filterBox){
      $(document).trigger('event-data-filter:changed')
    },
    'onItemsLoad': function(response, page){
      if (response.find('div[data-content="totals-results"]').length > 0){
        $('#columns-scoller-arrows').removeClass('hide')
        $('#event-data-totals').html(response.find('div[data-content="totals-results"]').html())
      }
    },
    'onItemsChange': function(response, page){
      if ($('#event-data-list .resource-item').length > 0) {
        $('#list-tools').show()
      } else {
        $('#list-tools').hide()
      }
    }
  });



  $('#columns-scoller-arrows .right-arrow').on('click', function(){
    var $lastItem = $('.results-box-container>span:last-child:first');
    if (($lastItem.offset().left + $lastItem.width()) > $(this).offset().left ) {
      scroll = $('#list-view').data('scroll');
      if (typeof scroll == 'undefined'){
        scroll = 1;
      }
      $('#list-view').addClass('scroll-'+scroll).data('scroll', scroll + 1);
    }
    if (($lastItem.offset().left + $lastItem.width()) <= $(this).offset().left + ($lastItem.width()*2) ) {
      $('#list-view').addClass('scroll-last');
    }
  });

  $('#columns-scoller-arrows .left-arrow').on('click', function(){
    scroll = $('#list-view').data('scroll');
    $('#list-view').removeClass('scroll-last')
    if (scroll && scroll > 0){
      scroll = scroll-1;
      $('#list-view').removeClass('scroll-'+scroll).data('scroll', Math.max(scroll,1));
    }
  });

  $(window).bind('resize',function(){
    var $lastItem = $('.results-box-container>span:last-child:first');
    if ($lastItem.length > 0){
      if (($lastItem.offset().left + $lastItem.width()) <= $('#columns-scoller-arrows .right-arrow').offset().left ) {
         $('#list-view').addClass('scroll-last');
      } else {
        $('#list-view').removeClass('scroll-last');
      }
    }
  })

app/views/results/event_data/items.html.slim
div data-content="items" data-total="#{collection_count}" data-pages="#{total_pages}" data-page="#{params[:page] || 1}"

  = render collection: collection, partial: 'event_data', as: :event

- if params[:page].nil? || params[:page] == '1'
  div data-content="totals-results"
    = render 'totals'

app/views/results/event_data/new_download.js.slim
|
  var downloadDialog = bootbox.dialog('#{j render('download')}', [{
    "label" : "Cancel",
    "class" : "btn btn-primary",
    "callback": function() {
        downloadDialog.modal('hide');
        if (downloadInterval){
          clearInterval(downloadInterval)
        }
    }
  }], {'onEscape': false, animate: (!$.fx.off)})

  var downloadInterval = setInterval(function(){
    $.get('#{download_status_results_event_data_url(@download.id, format: :json)}', function(response){
      if (response.status == 'completed') {
        clearInterval(downloadInterval);
        downloadDialog.modal('hide');
        window.location = response.url;
      }
    })
  }, 3000)