config/routes.rb
Brandscopic::Application.routes.draw do

  apipie if ENV['WEB']

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end

        resources :events, only: [:index, :show, :create, :update] do
          resources :photos, only: [:index, :create, :update] do
            get :form, on: :collection
          end
          resources :event_expenses, only: [:index, :create] do
            get :form, on: :collection
          end
          resources :tasks, only: [:index]
          resources :comments, only: [:index, :create, :update, :destroy]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
          end
        end

        # To allow CORS for any API action
        match ':path1(/:path2(/:path3(/:path4)))', via: :options, to: 'api#options'

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          get :stats, on: :member
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [] do
          member do
            get :comments
          end
          collection do
            get :mine, to: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, to: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end
      end
    end
  end

  if ENV['WEB']
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    mount Resque::Server.new, at: '/resque' unless Rails.env.test?
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  get '/users/complete-profile', to: 'users#complete', as: :complete_profile
  put '/users/update-profile', to: 'users#update_profile', as: :update_profile
  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }

  get 'countries/states'

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  namespace :results do
    resources :event_data, only: [:index] do
      get :items, on: :collection
    end
    resources :comments, only: [:index] do
      get :items, on: :collection
    end
    resources :photos, only: [:index] do
      get :items, on: :collection
      get :autocomplete, on: :collection
      get :filters, on: :collection
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :expenses, only: [:index] do
      get :items, on: :collection
    end
    resources :surveys, only: [:index] do
      get :items, on: :collection
    end
    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    resources :reports, only: [:index, :new, :create, :edit, :update, :show] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      get :deactivate, on: :member
      get :activate, on: :member
      post :preview, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'
    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'
  end

  namespace :analysis do
    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'
  end

  scope '/research' do
    resources :venues, only: [:index, :show] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      get :filters, on: :collection
      get :items, on: :collection
      resources :events, only: [:new, :create]
      resources :activities, only: [:new, :create] do
        get :form, on: :collection
      end
    end
  end

  resources :roles, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
    end
  end

  resources :company_users, except: [:new, :create, :destroy], path: 'users' do
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    get :profile, on: :collection
    get :autocomplete, on: :collection
    get :time_zone_change, on: :collection
    post :time_zone_change, on: :collection
    put :time_zone_update, on: :collection
    get :event, via: :get, on: :collection # List of users by event
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    resources :goals, only: [:create, :update, :edit, :new]
    resources :tasks do
      member do
        get :deactivate
        get :activate
      end
    end
    member do
      post :verify_phone
      get :send_code
      get :deactivate
      get :activate
      post :enable_campaigns
      post :disable_campaigns
      get :select_campaigns
      delete :remove_campaign
      post :add_campaign
      get :edit_communications
    end
  end

  resources :teams, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
      match 'members/:member_id' => 'teams#delete_member', via: :delete, as: :delete_member
      match 'members/new' => 'teams#new_member', via: :get, as: :new_member
      match 'members' => 'teams#add_members', via: :post, as: :add_member
    end
  end

  resources :kpis, only: [:index]

  resources :campaigns, except: [:destroy] do
    resources :areas_campaigns, only: [:edit, :update] do
      post :exclude_place, on: :member
      post :include_place, on: :member
    end

    resources :brands, only: [:index]
    resources :kpis, only: [:new, :create, :edit, :update]
    resources :activity_types, only: [] do
      get :set_goal
    end
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html
    get :find_similar_kpi, on: :collection
    member do
      get :post_event_form
      post :update_post_event_form
      get :deactivate
      get :activate
      get :places
      match 'members/:member_id' => 'campaigns#delete_member', via: :delete, as: :delete_member
      match 'teams/:team_id' => 'campaigns#delete_member', via: :delete, as: :delete_team
      match 'members/new' => 'campaigns#new_member', via: :get, as: :new_member
      match 'members' => 'campaigns#add_members', via: :post, as: :add_member
      match 'members' => 'campaigns#members', via: :get, as: :members
      match 'teams' => 'campaigns#teams', via: :get, as: :teams
      match 'tab/:tab' => 'campaigns#tab', via: :get, as: :tab, constraints: { tab: /staff|places|date_ranges|day_parts|documents|kpis/ }

      match 'date_ranges/new' => 'campaigns#new_date_range', via: :get, as: :new_date_range
      match 'date_ranges' => 'campaigns#add_date_range', via: :post, as: :add_date_range

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id            :integer          not null, primary key
#  event_id      :integer
#  created_by_id :integer
#  updated_by_id :integer
#  active        :boolean          default(TRUE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Survey < ActiveRecord::Base
  belongs_to :event

  has_many :surveys_answers, autosave: true, inverse_of: :survey

  accepts_nested_attributes_for :surveys_answers

  delegate :company_id, to: :event

  after_save :reindex_event

  def brands
    event.campaign.survey_brands
  end

  def age
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.age.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def gender
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.gender.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def ethnicity
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.ethnicity.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def activate!
    update_attribute :active, true
  end

  def deactivate!
    update_attribute :active, false
  end

  def answer_for(question_id, brand_id, kpi_id = nil)
    if kpi_id.nil?
      surveys_answers.select { |a| a.question_id == question_id && a.brand_id == brand_id }.first || surveys_answers.build(question_id: question_id, brand_id: brand_id)
    else
      surveys_answers.select { |a| a.question_id == question_id && a.kpi_id == kpi_id }.first || surveys_answers.build(question_id: question_id, kpi_id: kpi_id)
    end
  end

  protected

  def reindex_event
    # if this is the first survey for the event, then reindex it to set the flag "has_surveys" true
    if event.present? && event.surveys.count == 1
      Sunspot.index event
    end
  end
end

app/controllers/results/surveys_controller.rb
class Results::SurveysController < FilteredController
  defaults resource_class: ::Event
  respond_to :xls, only: :index

  helper_method :expenses_total, :return_path

  private

  def search_params
    @search_params ||= begin
      super
      unless @search_params.key?(:user) && !@search_params[:user].empty?
        @search_params[:with_surveys_only] = true
      end
      @search_params
    end
  end

  def authorize_actions
    authorize! :index_results, Survey
  end

  def return_path
    results_reports_path
  end
end

app/controllers/surveys_controller.rb
class SurveysController < FilteredController
  belongs_to :event
  respond_to :js, only: [:new, :create, :edit, :update]
  actions :new, :create, :edit, :update

  include DeactivableHelper

  protected

  def permitted_params
    params.permit(survey: { surveys_answers_attributes: [:id, :brand_id, :question_id, :answer, :kpi_id] })[:survey]
  end
end

app/views/surveys/_form.html.slim
#survey-form
  = simple_nested_form_for([parent, resource], html: { :multipart => true, class: 'survey_form' }, remote: true) do |f|
    = f.error_notification
    .form-inputs
      fieldset
        legend Demographics
        - Kpi.where('module' => 'demographics' ).each do |kpi|
          .demograpics-module
            = f.simple_fields_for :surveys_answers, resource.answer_for(1, nil, kpi.id) do |qf|
              = qf.hidden_field :kpi_id
              = qf.hidden_field :question_id
              = qf.input :answer, collection: kpi.kpis_segments.map{|s| [s.text, s.id]}, as: :radio_buttons, label: kpi.name, required: true

      fieldset
        legend.competitive Competitive awareness & usage

        p For each of the following brands, please let us know if you have purchased the product in the past 12 months, are aware of the product, or are unaware of the product
        ul.competitive
          li
            .titles
              span PURCHASED
              span AWARE
              span UNAWARE
          li
            - resource.brands.each do |brand|
              = f.simple_fields_for :surveys_answers, resource.answer_for(1, brand.id) do |qf|
                .row-fluid.control-group id="question-1-brand-#{brand.id}"
                  label.radio-brand
                    = brand.name
                  .radio-group
                    = qf.hidden_field :brand_id
                    = qf.hidden_field :question_id
                    label.radio= qf.radio_button :answer, 'purchased', class: 'required'
                    label.radio= qf.radio_button :answer, 'aware', class: 'required'
                    label.radio= qf.radio_button :answer, 'unaware', class: 'required'


        p For each brand that you have used, approximately how much do you spend each month?

        ul
          - resource.brands.each do |brand|
            li
              = f.simple_fields_for :surveys_answers, resource.answer_for(2, brand.id) do |qf|
                .row-fluid.control-group id="question-2-brand-#{brand.id}" data-observe="#question-1-brand-#{brand.id}" data-observe-value="purchased"
                  .hidden-label
                    label.radio= brand.name
                    = qf.hidden_field :brand_id
                    = qf.hidden_field :question_id

                  .hidden-field
                    .add-on $
                    = qf.text_field :answer, class: 'required'

      fieldset
        legend.conversion Conversion likehood

        p For each of the following brands, please let us know how likely you are to purchase the brand in the next 12 months? Please answer on a 1 to 5 scale where 1 = not at all likely and 5 = very likely.

        ul.conversion
          li
            .titles
              span
                | VERY UNLIKELY
                br
                | 1
              span 2
              span 3
              span 4
              span
                | VERY LIKELY
                br
                | 5
          - resource.brands.each do |brand|
            li
              = f.simple_fields_for :surveys_answers, resource.answer_for(3, brand.id) do |qf|
                .row-fluid.control-group
                  label.radio-brand= brand.name
                  .radio-group
                    = qf.hidden_field :brand_id
                    = qf.hidden_field :question_id
                    label.radio= qf.radio_button :answer, '1', class: 'required'
                    label.radio= qf.radio_button :answer, '2', class: 'required'
                    label.radio= qf.radio_button :answer, '3', class: 'required'
                    label.radio= qf.radio_button :answer, '4', class: 'required'
                    label.radio= qf.radio_button :answer, '5', class: 'required'


        p How likely are you to recommend the brand to a friend?  Please answer on a 0 to 10 scale where 0 is not at all likely and 10 = extremely likely

        ul.recommend
          li
            .titles
              span
                | VERY UNLIKELY
                br
                | 1
              span 2
              span 3
              span 4
              span 5
              span 6
              span 7
              span 8
              span 9
              span
                | VERY LIKELY
                br
                | 10
          tbody
            - resource.brands.each do |brand|
              = f.simple_fields_for :surveys_answers, resource.answer_for(4, brand.id) do |qf|
                .row-fluid.control-group
                    label.radio-brand= brand.name
                    .radio-group
                      = qf.hidden_field :brand_id
                      = qf.hidden_field :question_id
                      label.radio= qf.radio_button :answer, '1', class: 'required'
                      label.radio= qf.radio_button :answer, '2', class: 'required'
                      label.radio= qf.radio_button :answer, '3', class: 'required'
                      label.radio= qf.radio_button :answer, '4', class: 'required'
                      label.radio= qf.radio_button :answer, '5', class: 'required'
                      label.radio= qf.radio_button :answer, '6', class: 'required'
                      label.radio= qf.radio_button :answer, '7', class: 'required'
                      label.radio= qf.radio_button :answer, '8', class: 'required'
                      label.radio= qf.radio_button :answer, '9', class: 'required'
                      label.radio= qf.radio_button :answer, '10', class: 'required'

    .form-actions
      = f.button :submit, 'Save', id: 'submit-expense-btn', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
      = "&nbsp;".html_safe
      = f.button :button, 'Cancel', class: 'btn btn-cancel'

javascript:
  $('[data-observe]').each(function(index, row){
    var $row = $(row);
    $($row.data('observe')+' input[type=radio]').change(function(){
      if ($(this).val() != $row.data('observe-value')){
        $row.find('input[type=text][name*=answer]').val('')
        $row.hide().find('.required').removeClass('required')
      } else {
        $row.show().find('input[type=text]').addClass('required')
      }
    })
    if ($($row.data('observe')+' input[type=radio]:checked').val() != $row.data('observe-value')) {
      $row.hide().find('.required').removeClass('required');
      $row.find('input[type=text][name*=answer]').val('')
    } else {
      $row.show().find('input[type=text]').addClass('required');
    }
  });

app/views/surveys/_settings.slim
- @form_modal_class = 'modal-xlarge'

app/views/surveys/_survey.html.slim
li id="survey_#{survey.id}"
  span
    .survey-age
      - if age = survey.age
        = "#{age} year old"
    = "#{survey.ethnicity} #{survey.gender}"
  span.date
    = format_date(survey.created_at)
    br>/
    | Completed
  span.date
    = format_date(survey.updated_at)
    br>/
    | Modified
  span.pull-right
    = link_to '', edit_event_survey_path(survey.event, survey), remote: true, class: 'icon-edit' if can?(:edit, survey)
    - if can?(:deactivate, survey)
      = link_to '', deactivate_event_survey_path(survey.event, survey), remote: true, class: 'icon-rounded-disable', data: { confirm: I18n.t('confirmation.deactivate_confirm_message', model: survey.class.name)} if survey.active?
      = link_to '', activate_event_survey_path(survey.event, survey), remote: true, class: 'icon-rounded-ok',title: I18n.t('confirmation.active') unless survey.active?

app/views/surveys/create.js.slim
- if resource.errors.any?
	- resource.surveys_answers.select{|a| !a.valid? }.each{|a| puts a.errors.inspect }
	= render 'form_dialog'
- else
	|
	  $('.bootbox.modal').modal('hide');
	  $('#event-surveys-list').html('#{j render(parent.surveys)}')