config/routes.rb
Brandscopic::Application.routes.draw do

  apipie if ENV['WEB']

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end

        resources :events, only: [:index, :show, :create, :update] do
          resources :photos, only: [:index, :create, :update] do
            get :form, on: :collection
          end
          resources :event_expenses, only: [:index, :create] do
            get :form, on: :collection
          end
          resources :tasks, only: [:index]
          resources :comments, only: [:index, :create, :update, :destroy]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
          end
        end

        # To allow CORS for any API action
        match ':path1(/:path2(/:path3(/:path4)))', via: :options, to: 'api#options'

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          get :stats, on: :member
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [] do
          member do
            get :comments
          end
          collection do
            get :mine, to: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, to: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end
      end
    end
  end

  if ENV['WEB']
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    mount Resque::Server.new, at: '/resque' unless Rails.env.test?
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  get '/users/complete-profile', to: 'users#complete', as: :complete_profile
  put '/users/update-profile', to: 'users#update_profile', as: :update_profile
  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }

  get 'countries/states'

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  namespace :results do
    resources :event_data, only: [:index] do
      get :items, on: :collection
    end
    resources :comments, only: [:index] do
      get :items, on: :collection
    end
    resources :photos, only: [:index] do
      get :items, on: :collection
      get :autocomplete, on: :collection
      get :filters, on: :collection
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :expenses, only: [:index] do
      get :items, on: :collection
    end
    resources :surveys, only: [:index] do
      get :items, on: :collection
    end
    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    resources :reports, only: [:index, :new, :create, :edit, :update, :show] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      get :deactivate, on: :member
      get :activate, on: :member
      post :preview, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'
    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'
  end

  namespace :analysis do
    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'
  end

  scope '/research' do
    resources :venues, only: [:index, :show] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      get :filters, on: :collection
      get :items, on: :collection
      resources :events, only: [:new, :create]
      resources :activities, only: [:new, :create] do
        get :form, on: :collection
      end
    end
  end

  resources :roles, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
    end
  end

  resources :company_users, except: [:new, :create, :destroy], path: 'users' do
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    get :profile, on: :collection
    get :autocomplete, on: :collection
    get :time_zone_change, on: :collection
    post :time_zone_change, on: :collection
    put :time_zone_update, on: :collection
    get :event, via: :get, on: :collection # List of users by event
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    resources :goals, only: [:create, :update, :edit, :new]
    resources :tasks do
      member do
        get :deactivate
        get :activate
      end
    end
    member do
      post :verify_phone
      get :send_code
      get :deactivate
      get :activate
      post :enable_campaigns
      post :disable_campaigns
      get :select_campaigns
      delete :remove_campaign
      post :add_campaign
      get :edit_communications
    end
  end

  resources :teams, except: [:destroy] do
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html

    member do
      get :deactivate
      get :activate
      match 'members/:member_id' => 'teams#delete_member', via: :delete, as: :delete_member
      match 'members/new' => 'teams#new_member', via: :get, as: :new_member
      match 'members' => 'teams#add_members', via: :post, as: :add_member
    end
  end

  resources :kpis, only: [:index]

  resources :campaigns, except: [:destroy] do
    resources :areas_campaigns, only: [:edit, :update] do
      post :exclude_place, on: :member
      post :include_place, on: :member
    end

    resources :brands, only: [:index]
    resources :kpis, only: [:new, :create, :edit, :update]
    resources :activity_types, only: [] do
      get :set_goal
    end
    resources :placeables, only: [:new] do
      post :add_area, on: :collection
      delete :remove_area, on: :collection
    end
    resources :places, only: [:destroy, :create]
    get :autocomplete, on: :collection
    get :filters, on: :collection, format: :json
    get :items, on: :collection, format: :html
    get :find_similar_kpi, on: :collection
    member do
      get :post_event_form
      post :update_post_event_form
      get :deactivate
      get :activate
      get :places
      match 'members/:member_id' => 'campaigns#delete_member', via: :delete, as: :delete_member
      match 'teams/:team_id' => 'campaigns#delete_member', via: :delete, as: :delete_team
      match 'members/new' => 'campaigns#new_member', via: :get, as: :new_member
      match 'members' => 'campaigns#add_members', via: :post, as: :add_member
      match 'members' => 'campaigns#members', via: :get, as: :members
      match 'teams' => 'campaigns#teams', via: :get, as: :teams
      match 'tab/:tab' => 'campaigns#tab', via: :get, as: :tab, constraints: { tab: /staff|places|date_ranges|day_parts|documents|kpis/ }

      match 'date_ranges/new' => 'campaigns#new_date_range', via: :get, as: :new_date_range
      match 'date_ranges' => 'campaigns#add_date_range', via: :post, as: :add_date_range

app/views/company_users/_add_area.js.slim
|
	$('#company_user-areas-list').html('#{j render partial: 'company_users/area', collection: resource.areas.order('areas.name ASC'), locals: {resource: resource}}');

app/views/company_users/_area.html.slim
.span3.area-user.clearfix.hover-item id="company_user-area-#{area.id}"
  .pull-left
  	i.icon-wired-map
    = area.name
  .pull-right
    = link_to '',  remove_area_company_user_placeables_path(resource, area: area.id), method: :delete, remote: true, class: 'icon-remove-circle', title: 'Remove Area'

app/views/company_users/_campaign.html.slim
.span4.user-campaign.hover-item id="company_user-campaign-#{campaign.id}"
  .pull-left
    = campaign.name
  .pull-right
    = link_to '', remove_campaign_company_user_path(resource, {campaign_id: campaign.id}.merge( parent.nil?  ? {}  : {parent_type: parent.class.name, parent_id: parent.id})), method: :delete, remote: true, class: 'icon-remove-circle', title: 'Remove Campaign'

app/views/company_users/_campaigns.html.slim
/ / CAMPAIGNS ASSIGNED TO THE USER DIRECTLY
/ .campaigns-group
/   .campaigns-group-body
/     .row-fluid.campaigns-list id="campaigns-company_user-#{resource.id}"
/         = render partial: 'company_users/campaign', collection: resource.campaigns, locals: {parent: nil}


/ CAMPAIGNS GROUPED BY BRAND
- brands_campaigns_list.each do |parent, info|
  = render partial: 'campaings_bucket', locals: {parent: parent, enabled: info[:enabled], campaigns: info[:campaigns]}


- if can?(:edit, resource)
  javascript:
    $(document).delegate('.toggle-off-btn', 'click', function(e){
      $(this).parent().addClass('active').removeClass('deactive');
      $.post('#{enable_campaigns_company_user_path(resource)}', {parent_id: $(this).data('parent-id'), parent_type: $(this).data('parent-type')});
      return false;
    });
    $(document).delegate('.toggle-on-btn', 'click', function(e){
      $(this).parent().addClass('inactive').removeClass('active');
      $.post('#{disable_campaigns_company_user_path(resource)}', {parent_id: $(this).data('parent-id'), parent_type: $(this).data('parent-type')});
      return false;
    });


/ Markup for new design
- if false
  .details_box.user-view
    .user-data
      h3 CAMPAIGNS

      .items-container
        .box.special-icon.brand-icon
          b example one - brand icon

        .box.special-icon.brand-icon
          b Absolut Bloody Incremental FY14

        .box.special-icon.brand-icon
          b Absolut Texas Incremental Mini

        .box.special-icon.brand-icon
          b Jameson Black Barrel Summer MBN FY14

        .box.special-icon.brand-icon
          b Jameson FY14

        .box.special-icon.brand-icon
          b example one - brand icon

      .items-container
        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b Jameson MBN FY14

        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b Kahla BA Incremental

        .box.special-icon.campaign-icon
          b example one - campaign icon

      = link_to "Add campaigns"

app/views/company_users/_campaings_bucket.html.slim
.campaigns-group
  .row-fluid.campaigns-group-header
    .pull-left
      div class="switch-toggle #{enabled ? 'active' : 'inactive'}" id="campaigns-toggle-#{parent.class.name}-#{parent.id}"
        a.btn.btn-small.toggle-on-btn href="#" id="toggle-bucket-off" title="Toggle OFF" data-parent-id="#{parent.id}" data-parent-type="#{parent.class.name}"
          .on ALL
          span
        a.btn.btn-small.toggle-off-btn href="#" id="toggle-bucket-on" title="Toggle ON" data-parent-id="#{parent.id}" data-parent-type="#{parent.class.name}"
          span
          .off
    .pull-left
      h4 = parent.name



  .campaigns-group-body
    .row-fluid.campaigns-list id="campaigns-#{parent.class.name}-#{parent.id}"
        = render partial: 'company_users/campaign', collection: campaigns, locals: {parent: parent}

    .row-fluid
      = link_to '', select_campaigns_company_user_path(resource, parent_type: parent.class.name, parent_id: parent.id), remote: true, class: 'icon-plus-sign', id: "btn-add-campaign-#{parent.class.name}-#{parent.id}", style: "display: #{enabled ? 'none' : 'inline'};"

app/views/company_users/_form.html.slim
- remote ||= false
- is_admin = can?(:super_update, resource)
= simple_form_for(resource, remote: remote || false) do |f|
  = f.error_notification

  .form-inputs
    = f.simple_fields_for :user do |uf|
      .row-fluid.users
        .span6
          = uf.input :first_name, input_html: {class: 'input-large'}, :autofocus => true
        .span6
          = uf.input :last_name, input_html: {class: 'input-large'}

      - if is_admin
        .row-fluid.users
            = f.association :teams, collection: company_teams.active.all, input_html: {class: 'input-xxlarge chosen-enabled'}
      .row-fluid.users
        = uf.input :email, input_html: {class: 'input-xxlarge'}
      .row-fluid.users
        = uf.input :phone_number, input_html: {class: 'input-xxlarge'}, required: !is_admin

      - if is_admin
        .row-fluid.users-teams-roles
          = f.input :role_id, as: :select, collection: current_company.roles.active, input_html: {class: 'input-large chosen-enabled'}
      - if resource.id == current_company_user.id || is_admin
        .row-fluid.users
            = uf.input :password, input_html: {class: 'input-xxlarge', minlength: 8, maxlength: 128}, hint: 'Password must contain at least 8 characters, at least 1 number, at least 1 lowercase character (a-z) and at least 1 uppercase character (A-Z)'
        .row-fluid.users
            = uf.input :password_confirmation, input_html: {class: 'input-xxlarge'}
        .row-fluid.users
          = uf.input :street_address, label: 'Address', input_html: {class: 'input-xxlarge'}, required: !is_admin
        .row-fluid.users
          = uf.input :unit_number, label: false, input_html: {class: 'input-xxlarge'}, required: false
        .row-fluid.users
          .span6
            = uf.input :country, input_html: {class: 'input-large chosen-enabled'}, priority: ['US'], iso_codes: true, required: !is_admin
          .span6
            = uf.input :city, input_html: {class: 'input-large'}, required: !is_admin
        .row-fluid.users
          .span6
            = uf.input :state, collection: (resource.country.present? ? Country.new(resource.country).states.map{|k, info| [info['name'],k]} : []), input_html: {class: 'input-large chosen-enabled'}, required: !is_admin
          .span6
            = uf.input :zip_code, input_html: {class: 'input-large'}, required: !is_admin
        .row-fluid.users-teams-roles
          = uf.input :time_zone, input_html: {class: 'input-large chosen-enabled'}, required: !is_admin

  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
    = "&nbsp;".html_safe
    = f.button :button, 'Cancel', class: 'btn btn-cancel'

- unless resource.time_zone.present?
  javascript:
    $('#company_user_user_attributes_time_zone').set_timezone({'mappings':#{ActiveSupport::TimeZone::MAPPING.invert.to_json.html_safe}});

coffee:
  $('#company_user_user_attributes_country').change () ->
    $.get '/countries/states.json', {country: $(this).val()}, (response) ->
      states = $('#company_user_user_attributes_state')
      val = states.val()
      states.html('<option></option>')
      if response.states
        for state in response.states
          option = $('<option>').val(state.id).html(state.name)
          if val is state.id
            option.attr('selected', 'selected')
          states.append(option)
      states.trigger('liszt:updated')

app/views/company_users/_help_tutorial.html.slim
- content_for :help_title do
  - if params[:id].present?
    | View and edit specific information about a user related to campaigns and goals
  - else
    | Invite and manage users from this area (dependent on your permissions). Invited users will get email welcome messages and be able to enter in their own personal information
.help-overlay-definitions
  //For index
  div data-target="#application-content" data-intro="Click anywhere or press Esc to close" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="top: -26px;"
  div data-target="#users-list li:nth-child(1) .user_name" data-intro="A users's name and their system access level" data-position="bottom" data-tooltip-style="bottom: -70px; left: -35px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_city" data-intro="A users's physical address" data-position="bottom" data-tooltip-style="bottom: -50px; left: -40px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_mail" data-intro="Contact email address" data-tooltip-style="bottom: -50px; left: -35px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_date" data-intro="The date of the last activity such as a user login" data-tooltip-style="bottom: -70px; left: -40px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(2) .tools" data-intro="Users can be deactivated or edited (e.g., access level, password change, time zone settings)" data-position="bottom" data-tooltip-style="width: 197px; left: -84px; bottom: -116px; padding-top: 0px;"
  div data-target="#search-box-filter" data-intro="Search for specific users by role, team and campaign" data-position="left" data-tooltip-style="top: -17px; left: -117px;"
  div data-target="#resource-filter-column" data-intro="Filter users by selecting multiple criteria" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 430px; left: -122px;"

  //For show
  div data-target=".padding-top-close-bar h2" data-intro="View the critical information about a user including their name, access level and contact information" data-position="right" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 20px; left: 320px;"
  div data-target=".links-data" data-intro="Edit or deactivate a user by clicking here" data-position="right"  data-tooltip-style="top: -7px; left: 85px;"
  div data-target="#user-places" data-intro="Add or remove users from Places or Areas (a defined group of places)" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="left: 480px; top: -32px; width: 180px;"
  div data-target=".switch-toggle:nth-child(1)" data-intro="Add or remove users from all campaigns in a brand by toggling this on/off" data-position="right" data-tooltip-style="top: -37px; right: -100px;"
  div data-target=".campaigns-group-body a.icon-plus-sign" data-intro="Click to add a user to a specific campaign" data-position="bottom" data-tooltip-style="top: 118px; left: -65px; padding-top: 0px;"
  //div data-target="a.icon-remove-circle" data-intro="Click to remove a user from an individual campaign" data-position="bottom" data-tooltip-style="top: 146px; left: -65px; padding-top: 0px;"
  div data-target=".btn-add-goal" data-intro="Add user-specific goals and start/end dates for those goals" data-position="right" data-tooltip-style="top: -18px; right: -110px;"
  div data-target="#resource-goals-list li:nth-child(1) a.edit" data-intro="Edit goals and start/end dates" data-tooltip-style="bottom: -46px; left: -50px; width: 130px; padding-top: 0;"

app/views/company_users/_place.html.slim
.span3.place.clearfix.hover-item id="company_user-place-#{place.id}"
  .pull-left
    .place-name
      = place.name
    .place-address
      = place.formatted_address
  .pull-right
    = link_to '',  company_user_place_path(resource, place), method: :delete, remote: true, class: 'icon-remove-circle', title: 'Remove Place'

app/views/company_users/_places.html.slim
= render partial: 'company_users/place', collection: resource.places, locals: {resource: resource}

/ Markup for new design
- if false
  .details_box.user-view

    .user-data

      h3 PLACES
      .items-container
        .box.special-icon.area-icon
          b Madison Area

        .box.special-icon.area-icon
          b Boston Area

        .box.special-icon.area-icon
          b Houston Area

        .box.special-icon.area-icon
          b Denver Area

        .box.special-icon.area-icon
          b example one - area icon

        .box.special-icon.area-icon
          b Metro New York Area


      .items-container
        .box.special-icon.venue-icon
          a href="#" example one - venue icon
          p 6251 East Pacific Coast Highway, Long Beach

        .box.special-icon.venue-icon
          a href="#" Bar & Dinner "PPTH"
          p 6251 East Pacific Coast Highway, Long Beach

        .box.special-icon.venue-icon
          a href="#" example one - venue icon
          p 6251 East Pacific Coast Highway, Long Beach

        .box.special-icon.venue-icon
          a href="#" Bar & Dinner "PPTH"
          p 6251 East Pacific Coast Highway, Long Beach

      = link_to "Add places"

app/views/company_users/_select_campaigns.html.slim
.resource-list.select-list
  - @campaigns.each do |campaign|
    .resource-item id="campaign-#{campaign.id}"
      .resource-item-link
        .text-large= campaign.name
        = campaign.description
      .resource-item-actions
        = link_to '', add_campaign_company_user_path(resource, parent_id: params[:parent_id], parent_type: params[:parent_type], campaign_id: campaign.id), remote: true, method: :post, data: {disable_with: '...'}, class: 'icon-plus-sign'

app/views/company_users/_send_code.html.slim
= simple_form_for(resource, url: verify_phone_company_user_path(resource), method: :post, remote: true) do |f|
  p= "We will send you a message to #{resource.phone_number} with a code."


  .form-actions
    = f.button :submit, 'Send', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
    = "&nbsp;".html_safe
    = f.button :button, 'Cancel', class: 'btn btn-cancel'

app/views/company_users/enable_campaigns.js.slim
|
  $('#campaigns-#{params[:parent_type]}-#{params[:parent_id]}').html('#{j render(partial: 'company_users/campaign', collection: @campaigns, locals: {parent: @parent})}')
  $('#btn-add-campaign-#{params[:parent_type]}-#{params[:parent_id]}').hide();

app/views/company_users/remove_campaign.js.slim
|
  $('#campaigns-#{params[:parent_type]}-#{params[:parent_id]} #company_user-campaign-#{params[:campaign_id]}').remove();
  $('#campaigns-toggle-#{params[:parent_type]}-#{params[:parent_id]}').removeClass('active').addClass('inactive');
  $('#btn-add-campaign-#{params[:parent_type]}-#{params[:parent_id]}').show();

app/views/company_users/time_zone_change.js.slim
|
  var tzmodal = bootbox.confirm($('<div>#{escape_javascript(render(partial: 'time_zone_change'))}</div>'), function(result){
    if (result){
      $.ajax({
          url: '#{time_zone_update_company_users_path(format: :js)}',
          type: 'PUT',
          data: {time_zone: '#{escape_javascript(params[:time_zone].html_safe)}'}
      });
    }
  });
		